import json
import random
from pathlib import Path


class AddressProvider_for_offline:
    city_suffixes = (
        'do Sul',
        'do Norte',
        'de Minas',
        'do Campo',
        'Grande',
        'da Serra',
        'do Oeste',
        'de Goiás',
        'Paulista',
        'da Mata',
        'Alegre',
        'da Praia',
        'das Flores',
        'das Pedras',
        'dos Dourados',
        'do Amparo',
        'do Galho',
        'da Prata',
        'Verde',
    )
    street_prefixes = (
        'Aeroporto',
        'Alameda',
        'Área',
        'Avenida',
        'Campo',
        'Chácara',
        'Colônia',
        'Condomínio',
        'Conjunto',
        'Distrito',
        'Esplanada',
        'Estação',
        'Estrada',
        'Favela',
        'Fazenda',
        'Feira',
        'Jardim',
        'Ladeira',
        'Lago',
        'Lagoa',
        'Largo',
        'Loteamento',
        'Morro',
        'Núcleo',
        'Parque',
        'Passarela',
        'Pátio',
        'Praça',
        'Praia',
        'Quadra',
        'Recanto',
        'Residencial',
        'Rodovia',
        'Rua',
        'Setor',
        'Sítio',
        'Travessa',
        'Trecho',
        'Trevo',
        'Vale',
        'Vereda',
        'Via',
        'Viaduto',
        'Viela',
        'Vila',
    )
    city_formats = (
        '{{last_name}}',
        '{{last_name}}',
        '{{last_name}}',
        '{{last_name}}',
        '{{last_name}} {{city_suffix}}',
        '{{last_name}} {{city_suffix}}',
        '{{last_name}} {{city_suffix}}',
        '{{last_name}} de {{last_name}}',
    )
    street_name_formats = (
        '{{street_prefix}} {{last_name}}',
        '{{street_prefix}} {{first_name}} {{last_name}}',
        '{{street_prefix}} de {{last_name}}',
    )

    street_address_formats = (
        '{{street_name}}',
        '{{street_name}}, {{building_number}}',
        '{{street_name}}, {{building_number}}',
        '{{street_name}}, {{building_number}}',
        '{{street_name}}, {{building_number}}',
        '{{street_name}}, {{building_number}}',
        '{{street_name}}, {{building_number}}',
    )

    address_formats = ('{{street_address}}\n{{bairro}}\n{{postcode}} {{city}} / {{estado_sigla}}',)

    building_number_formats = ('%', '%#', '%#', '%#', '%##')

    postcode_raw_formats = ('########',)
    postcode_all_formats = postcode_raw_formats + ('#####-###',)

    bairros = (
        'Aarão Reis',
        'Acaba Mundo',
        'Acaiaca',
        'Ademar Maldonado',
        'Aeroporto',
        'Aguas Claras',
        'Alípio De Melo',
        'Alpes',
        'Alta Tensão 1ª Seção',
        'Alta Tensão 2ª Seção',
        'Alto Caiçaras',
        'Alto Das Antenas',
        'Alto Dos Pinheiros',
        'Alto Vera Cruz',
        'Álvaro Camargos',
        'Ambrosina',
        'Andiroba',
        'Antonio Ribeiro De Abreu 1ª Seção',
        'Aparecida 7ª Seção',
        'Ápia',
        'Apolonia',
        'Araguaia',
        'Atila De Paiva',
        'Bacurau',
        'Bairro Das Indústrias Ii',
        'Baleia',
        'Barão Homem De Melo 1ª Seção',
        'Barão Homem De Melo 2ª Seção',
        'Barão Homem De Melo 3ª Seção',
        'Barreiro',
        'Beija Flor',
        'Beira Linha',
        'Bela Vitoria',
        'Belmonte',
        'Bernadete',
        'Betânia',
        'Biquinhas',
        'Boa Esperança',
        'Boa União 1ª Seção',
        'Boa União 2ª Seção',
        'Boa Viagem',
        'Boa Vista',
        'Bom Jesus',
        'Bonfim',
        'Bonsucesso',
        'Brasil Industrial',
        'Braúnas',
        'Buraco Quente',
        'Cabana Do Pai Tomás',
        'Cachoeirinha',
        'Caetano Furquim',
        'Caiçara - Adelaide',
        'Calafate',
        'Califórnia',
        'Camargos',
        'Campo Alegre',
        'Camponesa 1ª Seção',
        'Camponesa 2ª Seção',
        'Canaa',
        'Canadá',
        'Candelaria',
        'Capitão Eduardo',
        'Cardoso',
        'Casa Branca',
        'Castanheira',
        'Cdi Jatoba',
        'Cenaculo',
        'Céu Azul',
        'Chácara Leonina',
        'Cidade Jardim Taquaril',
        'Cinquentenário',
        'Colégio Batista',
        'Comiteco',
        'Concórdia',
        'Cônego Pinheiro 1ª Seção',
        'Cônego Pinheiro 2ª Seção',
        'Confisco',
        'Conjunto Bonsucesso',
        'Conjunto Califórnia I',
        'Conjunto Califórnia Ii',
        'Conjunto Capitão Eduardo',
        'Conjunto Celso Machado',
        'Conjunto Floramar',
        'Conjunto Jardim Filadélfia',
        'Conjunto Jatoba',
        'Conjunto Lagoa',
        'Conjunto Minas Caixa',
        'Conjunto Novo Dom Bosco',
        'Conjunto Paulo Vi',
        'Conjunto Providencia',
        'Conjunto Santa Maria',
        'Conjunto São Francisco De Assis',
        'Conjunto Serra Verde',
        'Conjunto Taquaril',
        'Copacabana',
        'Coqueiros',
        'Corumbiara',
        'Custodinha',
        'Das Industrias I',
        'Delta',
        'Diamante',
        'Distrito Industrial Do Jatoba',
        'Dom Bosco',
        'Dom Cabral',
        'Dom Joaquim',
        'Dom Silverio',
        'Dona Clara',
        'Embaúbas',
        'Engenho Nogueira',
        'Ermelinda',
        'Ernesto Nascimento',
        'Esperança',
        'Estrela',
        'Estrela Do Oriente',
        'Etelvina Carneiro',
        'Europa',
        'Eymard',
        'Fazendinha',
        'Flamengo',
        'Flavio De Oliveira',
        'Flavio Marques Lisboa',
        'Floramar',
        'Frei Leopoldo',
        'Gameleira',
        'Garças',
        'Glória',
        'Goiania',
        'Graça',
        'Granja De Freitas',
        'Granja Werneck',
        'Grota',
        'Grotinha',
        'Guarani',
        'Guaratã',
        'Havaí',
        'Heliopolis',
        'Horto Florestal',
        'Inconfidência',
        'Indaiá',
        'Independência',
        'Ipe',
        'Itapoa',
        'Itatiaia',
        'Jaqueline',
        'Jaraguá',
        'Jardim Alvorada',
        'Jardim Atlântico',
        'Jardim Do Vale',
        'Jardim Dos Comerciarios',
        'Jardim Felicidade',
        'Jardim Guanabara',
        'Jardim Leblon',
        'Jardim Montanhês',
        'Jardim São José',
        'Jardim Vitoria',
        'Jardinópolis',
        'Jatobá',
        'João Alfredo',
        'João Paulo Ii',
        'Jonas Veiga',
        'Juliana',
        'Lagoa',
        'Lagoinha',
        'Lagoinha Leblon',
        'Lajedo',
        'Laranjeiras',
        'Leonina',
        'Leticia',
        'Liberdade',
        'Lindéia',
        'Lorena',
        'Madre Gertrudes',
        'Madri',
        'Mala E Cuia',
        'Manacas',
        'Mangueiras',
        'Mantiqueira',
        'Marajó',
        'Maravilha',
        'Marçola',
        'Maria Goretti',
        'Maria Helena',
        'Maria Tereza',
        'Maria Virgínia',
        'Mariano De Abreu',
        'Marieta 1ª Seção',
        'Marieta 2ª Seção',
        'Marieta 3ª Seção',
        'Marilandia',
        'Mariquinhas',
        'Marmiteiros',
        'Milionario',
        'Minas Brasil',
        'Minas Caixa',
        'Minaslandia',
        'Mineirão',
        'Miramar',
        'Mirante',
        'Mirtes',
        'Monsenhor Messias',
        'Monte Azul',
        'Monte São José',
        'Morro Dos Macacos',
        'Nazare',
        'Nossa Senhora Aparecida',
        'Nossa Senhora Da Aparecida',
        'Nossa Senhora Da Conceição',
        'Nossa Senhora De Fátima',
        'Nossa Senhora Do Rosário',
        'Nova America',
        'Nova Cachoeirinha',
        'Nova Cintra',
        'Nova Esperança',
        'Nova Floresta',
        'Nova Gameleira',
        'Nova Pampulha',
        'Novo Aarão Reis',
        'Novo Das Industrias',
        'Novo Glória',
        'Novo Santa Cecilia',
        'Novo Tupi',
        'Oeste',
        'Olaria',
        "Olhos D'água",
        'Ouro Minas',
        'Pantanal',
        'Paquetá',
        'Paraíso',
        'Parque São José',
        'Parque São Pedro',
        'Paulo Vi',
        'Pedreira Padro Lopes',
        'Penha',
        'Petropolis',
        'Pilar',
        'Pindorama',
        'Pindura Saia',
        'Piraja',
        'Piratininga',
        'Pirineus',
        'Pompéia',
        'Pongelupe',
        'Pousada Santo Antonio',
        'Primeiro De Maio',
        'Providencia',
        'Ribeiro De Abreu',
        'Rio Branco',
        'Salgado Filho',
        'Santa Amelia',
        'Santa Branca',
        'Santa Cecilia',
        'Santa Cruz',
        'Santa Helena',
        'Santa Inês',
        'Santa Isabel',
        'Santa Margarida',
        'Santa Maria',
        'Santa Rita',
        'Santa Rita De Cássia',
        'Santa Sofia',
        'Santa Terezinha',
        'Santana Do Cafezal',
        'Santo André',
        'São Benedito',
        'São Bernardo',
        'São Cristóvão',
        'São Damião',
        'São Francisco',
        'São Francisco Das Chagas',
        'São Gabriel',
        'São Geraldo',
        'São Gonçalo',
        'São João',
        'São João Batista',
        'São Jorge 1ª Seção',
        'São Jorge 2ª Seção',
        'São Jorge 3ª Seção',
        'São José',
        'São Marcos',
        'São Paulo',
        'São Salvador',
        'São Sebastião',
        'São Tomaz',
        'São Vicente',
        'Satelite',
        'Saudade',
        'Senhor Dos Passos',
        'Serra Do Curral',
        'Serra Verde',
        'Serrano',
        'Solar Do Barreiro',
        'Solimoes',
        'Sport Club',
        'Suzana',
        'Taquaril',
        'Teixeira Dias',
        'Tiradentes',
        'Tirol',
        'Tres Marias',
        'Trevo',
        'Túnel De Ibirité',
        'Tupi A',
        'Tupi B',
        'União',
        'Unidas',
        'Universitário',
        'Universo',
        'Urca',
        'Vale Do Jatoba',
        'Varzea Da Palma',
        'Venda Nova',
        'Ventosa',
        'Vera Cruz',
        'Vila Aeroporto',
        'Vila Aeroporto Jaraguá',
        'Vila Antena',
        'Vila Antena Montanhês',
        'Vila Atila De Paiva',
        'Vila Bandeirantes',
        'Vila Barragem Santa Lúcia',
        'Vila Batik',
        'Vila Betânia',
        'Vila Boa Vista',
        'Vila Calafate',
        'Vila Califórnia',
        'Vila Canto Do Sabiá',
        'Vila Cemig',
        'Vila Cloris',
        'Vila Copacabana',
        'Vila Copasa',
        'Vila Coqueiral',
        'Vila Da Amizade',
        'Vila Da Ária',
        'Vila Da Luz',
        'Vila Da Paz',
        'Vila Das Oliveiras',
        'Vila Do Pombal',
        'Vila Dos Anjos',
        'Vila Ecológica',
        'Vila Engenho Nogueira',
        'Vila Esplanada',
        'Vila Formosa',
        'Vila Fumec',
        'Vila Havaí',
        'Vila Independencia 1ª Seção',
        'Vila Independencia 2ª Seção',
        'Vila Independencia 3ª Seção',
        'Vila Inestan',
        'Vila Ipiranga',
        'Vila Jardim Alvorada',
        'Vila Jardim Leblon',
        'Vila Jardim São José',
        'Vila Madre Gertrudes 1ª Seção',
        'Vila Madre Gertrudes 2ª Seção',
        'Vila Madre Gertrudes 3ª Seção',
        'Vila Madre Gertrudes 4ª Seção',
        'Vila Maloca',
        'Vila Mangueiras',
        'Vila Mantiqueira',
        'Vila Maria',
        'Vila Minaslandia',
        'Vila Nossa Senhora Do Rosário',
        'Vila Nova',
        'Vila Nova Cachoeirinha 1ª Seção',
        'Vila Nova Cachoeirinha 2ª Seção',
        'Vila Nova Cachoeirinha 3ª Seção',
        'Vila Nova Dos Milionarios',
        'Vila Nova Gameleira 1ª Seção',
        'Vila Nova Gameleira 2ª Seção',
        'Vila Nova Gameleira 3ª Seção',
        'Vila Nova Paraíso',
        'Vila Novo São Lucas',
        'Vila Oeste',
        "Vila Olhos D'água",
        'Vila Ouro Minas',
        'Vila Paquetá',
        'Vila Paraíso',
        'Vila Petropolis',
        'Vila Pilar',
        'Vila Pinho',
        'Vila Piratininga',
        'Vila Piratininga Venda Nova',
        'Vila Primeiro De Maio',
        'Vila Puc',
        'Vila Real 1ª Seção',
        'Vila Real 2ª Seção',
        'Vila Rica',
        'Vila Santa Monica 1ª Seção',
        'Vila Santa Monica 2ª Seção',
        'Vila Santa Rosa',
        'Vila Santo Antônio',
        'Vila Santo Antônio Barroquinha',
        'Vila São Dimas',
        'Vila São Francisco',
        'Vila São Gabriel',
        'Vila São Gabriel Jacui',
        'Vila São Geraldo',
        'Vila São João Batista',
        'Vila São Paulo',
        'Vila São Rafael',
        'Vila Satélite',
        'Vila Sesc',
        'Vila Sumaré',
        'Vila Suzana Primeira Seção',
        'Vila Suzana Segunda Seção',
        'Vila Tirol',
        'Vila Trinta E Um De Março',
        'Vila União',
        'Vila Vista Alegre',
        'Virgínia',
        'Vista Alegre',
        'Vista Do Sol',
        'Vitoria',
        'Vitoria Da Conquista',
        'Xangri-Lá',
        'Xodo-Marize',
        'Zilah Sposito',
        'Outro',
        'Novo São Lucas',
        'Esplanada',
        'Estoril',
        'Novo Ouro Preto',
        'Ouro Preto',
        'Padre Eustáquio',
        'Palmares',
        'Palmeiras',
        'Vila De Sá',
        'Floresta',
        'Anchieta',
        'Aparecida',
        'Grajaú',
        'Planalto',
        'Bandeirantes',
        'Gutierrez',
        'Jardim América',
        'Renascença',
        'Barro Preto',
        'Barroca',
        'Sagrada Família',
        'Ipiranga',
        'Belvedere',
        'Santa Efigênia',
        'Santa Lúcia',
        'Santa Monica',
        'Vila Jardim Montanhes',
        'Santa Rosa',
        'Santa Tereza',
        'Buritis',
        'Vila Paris',
        'Santo Agostinho',
        'Santo Antônio',
        'Caiçaras',
        'São Bento',
        'Prado',
        'Lourdes',
        'Fernão Dias',
        'Carlos Prates',
        'Carmo',
        'Luxemburgo',
        'São Lucas',
        'São Luiz',
        'Mangabeiras',
        'São Pedro',
        'Horto',
        'Cidade Jardim',
        'Castelo',
        'Cidade Nova',
        'Savassi',
        'Serra',
        'Silveira',
        'Sion',
        'Centro',
        'Alto Barroca',
        'Nova Vista',
        'Coração De Jesus',
        'Coração Eucarístico',
        'Funcionários',
        'Cruzeiro',
        'João Pinheiro',
        'Nova Granada',
        'Nova Suíça',
        'Itaipu',
    )

    def street_prefix(self) -> str:
        """
        :example: 'rua'
        """
        return self.random_element(self.street_prefixes)

    def bairro(self) -> str:
        """
        Randomly returns a bairro (neighborhood) name.
        The names were taken from the city of Belo Horizonte - Minas Gerais
        :example: 'Serra'
        """
        return self.random_element(self.bairros)

    # aliases
    def neighborhood(self) -> str:
        return self.bairro()

    def random_element(self, elements):
        """
        Returns a random element from a sequence.

        Args:
            elements: A sequence (list, tuple) to pick a random element from

        Returns:
            A random element from the sequence
        """
        return random.choice(elements)

    def building_number(self) -> str:
        """
        Returns a random building number.

        Returns:
            A random building number as a string
        """
        return str(random.randint(1, 999))

    def last_name(self) -> str:
        """
        Returns a random last name.

        Returns:
            A random last name as a string
        """
        last_names = [
            'Silva',
            'Santos',
            'Oliveira',
            'Souza',
            'Rodrigues',
            'Ferreira',
            'Alves',
            'Pereira',
            'Lima',
            'Gomes',
            'Costa',
            'Ribeiro',
            'Martins',
            'Carvalho',
            'Almeida',
            'Lopes',
            'Soares',
            'Fernandes',
            'Vieira',
            'Barbosa',
            'Rocha',
            'Dias',
            'Nascimento',
            'Andrade',
            'Moreira',
            'Nunes',
            'Marques',
            'Machado',
            'Mendes',
            'Freitas',
            'Cardoso',
            'Ramos',
        ]
        return self.random_element(last_names)

    def first_name(self) -> str:
        """
        Returns a random first name.

        Returns:
            A random first name as a string
        """
        # Use the non_weighted_random_name method to get a random first name
        return self.non_weighted_random_name()

    def non_weighted_random_name(self, names_path: str = 'ptbr_sampler/data/names_data.json') -> str:
        """
        Returns a random name from the names data file without weighting.

        Args:
            names_path: Path to the names data JSON file

        Returns:
            A random name as a string
        """
        try:
            # Load names from the file
            with Path(names_path).open(encoding='utf-8') as f:
                names_data = json.load(f)

            # Extract all names from the data
            all_names = []
            for period_data in names_data.values():
                if isinstance(period_data, dict) and 'names' in period_data:
                    all_names.extend([name for name, _ in period_data['names']])

            # If no names were found, return a default name
            if not all_names:
                return 'João'

            # Return a random name
            return self.random_element(all_names)
        except (FileNotFoundError, json.JSONDecodeError, KeyError) as e:
            # In case of error, return a default name
            print(f'Warning: Could not load names from {names_path}: {e}')
            return 'Maria'
